##  merge :

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.DataFrame(
    {
        "Id" : [1,2,3,5],
        "Name" : ["Raj","Sahil","Rajesh","Rajveer"]
    })

df2 = pd.DataFrame(
    {
        "Id" : [1,2,3,4],
        "Marks" : [67,89,45,60],
        "Age" : [12,23,16,20]
    })

In [ ]:
df1

In [ ]:
df2

In [ ]:
pd.merge(df1,df2,on="Id")

In [ ]:
pd.merge(df1,df2,on="Id",how="inner")

In [ ]:
pd.merge(df1,df2,on="Id",how="outer")

In [ ]:
pd.merge(df1,df2,on="Id",how="left")

In [ ]:
pd.merge(df1,df2,on="Id",how="right")

In [ ]:
df = pd.DataFrame(
    {
        "Name" : ["Raj","Sahil","Rajesh","Rajveer"],
        "Marks" : [67,89,45,60],
        "Age" : [12,23,16,20]
    })

In [ ]:
df

In [ ]:
df.pivot(index="Name",columns="Marks",values="Age")

In [ ]:
df =  pd.DataFrame({
    "Date": ["2026-01-01", "2026-01-01", "2026-01-01", "2026-01-02"],
    "City": ["Chicago", "Austin", "Chicago", "Austin"],
    "Temperature": [32, 75, 30, 78]
})

In [ ]:
df.pivot(index="City",columns="Date",values="Temperature")

In [ ]:
output =  df.pivot_table(index="Date",columns="City",values="Temperature",aggfunc="sum")

In [ ]:
output

In [ ]:
df =  pd.DataFrame({
    "Date": ["2026-01-01", "2026-01-01", "2026-01-01", "2026-01-02"],
    "City": ["Chicago", "Austin", "Chicago", "Austin"],
    "Temperature": [32, 75, 30, 78]
})

In [55]:
df

         Date     City  Temperature
0  2026-01-01  Chicago           32
1  2026-01-01   Austin           75
2  2026-01-01  Chicago           30
3  2026-01-02   Austin           78

In [63]:
df.reindex(["A","B","C","D"],fill_value="0")

  Date City Temperature
A    0    0           0
B    0    0           0
C    0    0           0
D    0    0           0

In [ ]:
df[df["Temperature" > 50]]

## Join , Altering, labels, Groupby() & Transform()